#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Kazuki Fujita
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

result = ans * 2

print(result)
